#!/bin/bash

vara=""
varb=""

while getopts ":a:b:" opt; do
  case "${opt}" in
    a)
      vara=${OPTARG}
      ;;
    b)
      varb=${OPTARG}
      ;;
    :)
      echo "Error: -${OPTARG} requires an argument"
      exit 1
      ;;
    "?")
      exit 1
      ;;
  esac
done

if [[ $# -lt 1 ]]; then
  echo "you need to provide an option -a and or -b with an argument"
fi

if [[ $vara != "" ]]; then
  echo "$vara"
fi

if [[ $varb != "" ]]; then
  echo "$varb"
fi
